#!/bin/bash
myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`;

 red='\e[1;31m'
               green='\e[0;32m'
	       blue='\e[34m'
	       purple='\e[35m'
               NC='\e[0m'
			   
               echo "Connecting to Orang-Ganteng.com..."
			   sleep 1
			   
			   echo "Connecting to your ip : $myip ...."
               sleep 2
               
			   echo "Checking Permision..."
               sleep 1.5
               
			   echo -e "${green}Permission Accepted...${NC}"
               sleep 1

function create_user() {
	useradd -M $uname
	echo "$uname:$pass" | chpasswd
	usermod -e $expdate $uname

	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
	myip2="s/xxxxxxxxx/$myip/g";	
	wget -qO /tmp/client.ovpn "https://raw.githubusercontent.com/Y4suf/MyVPS/master/1194-client.ovpn"
	sed -i 's/remote xxxxxxxxx 1194/remote xxxxxxxxx 443/g' /tmp/client.ovpn
	sed -i $myip2 /tmp/client.ovpn
	echo ""
	echo "========================="
	echo "Host IP : $myip"
	echo "Port    : 443/22/80"
	echo "Squid   : 8080/3128"
	echo "========================="
	echo "Script by Orang Ganteng "
	echo "========================="
}

function renew_user() {
	echo "New expiration date for $uname: $expdate...";
	usermod -e $expdate $uname
}

function delete_user(){
	userdel $uname
}

function expired_users(){
	cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
	totalaccounts=`cat /tmp/expirelist.txt | wc -l`
	for((i=1; i<=$totalaccounts; i++ )); do
		tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
		username=`echo $tuserval | cut -f1 -d:`
		userexp=`echo $tuserval | cut -f2 -d:`
		userexpireinseconds=$(( $userexp * 86400 ))
		todaystime=`date +%s`
		if [ $userexpireinseconds -lt $todaystime ] ; then
			echo $username
		fi
	done
	rm /tmp/expirelist.txt
}

function not_expired_users(){
    cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
    totalaccounts=`cat /tmp/expirelist.txt | wc -l`
    for((i=1; i<=$totalaccounts; i++ )); do
        tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
        username=`echo $tuserval | cut -f1 -d:`
        userexp=`echo $tuserval | cut -f2 -d:`
        userexpireinseconds=$(( $userexp * 86400 ))
        todaystime=`date +%s`
        if [ $userexpireinseconds -gt $todaystime ] ; then
            echo $username
        fi
    done
	rm /tmp/expirelist.txt
}

function used_data(){
	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`
	myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`
	ifconfig $myint | grep "RX bytes" | sed -e 's/ *RX [a-z:0-9]*/Received: /g' | sed -e 's/TX [a-z:0-9]*/\nTransfered: /g'
}

	clear
	echo -e "\e[037;1m--------------- Selamat Datang Di Server - IP: $myip ---------------\e[0m"
	cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
	cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
	freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
	tram=$( free -m | awk 'NR==2 {print $2}' )
	swap=$( free -m | awk 'NR==4 {print $2}' )
	up=$(uptime|awk '{ $1=$2=$(NF-6)=$(NF-5)=$(NF-4)=$(NF-3)=$(NF-2)=$(NF-1)=$NF=""; print }')

	echo -e "\e[032;1mCPU Model:\e[0m $cname"
	echo -e "\e[032;1mNumber Of Cores:\e[0m $cores"
	echo -e "\e[032;1mCPU Frequency:\e[0m $freq MHz"
	echo -e "\e[032;1mTotal Amount Of Ram:\e[0m $tram MB"
	echo -e "\e[032;1mTotal Amount Of Swap:\e[0m $swap MB"
	echo -e "\e[032;1mSystem UpTime:\e[0m $up"
	echo -e "\e[032;1mScript Mod by:\e[0m Orang Ganteng | 0895703796928"
	echo "------------------------------------------------------------------------------"
	date +"                       #     A, %d-%m-%Y     #" 
        date +"                       #        %H:%M:%S %Z          #" 
	echo "------------------------------------------------------------------------------"
	echo -e "\e[036mSeputar Detail SSH & OpenVPN\e[0m"
	echo -e "  \e[032;1m 1\e[0m\e[037;1m)\e[0m \e[033;1mCreate Akun SSH/OpenVPN\e[0m (\e[37;1muser-add\e[0m)"
	echo -e "  \e[032;1m 2\e[0m\e[037;1m)\e[0m \e[033;1mGenerate Akun SSH/OpenVPN\e[0m (\e[37;1muser-gen\e[0m)"
	echo -e "  \e[032;1m 3\e[0m\e[037;1m)\e[0m \e[033;1mGenerate Akun Trial\e[0m (\e[37;1muser-trial\e[0m)"
	echo -e "  \e[032;1m 4\e[0m\e[037;1m)\e[0m \e[033;1mGanti Password Akun SSH/VPN\e[0m (\e[37;1muser-pass\e[0m)"
	echo -e "  \e[032;1m 5\e[0m\e[037;1m)\e[0m \e[033;1mTambah Masa Aktif Akun SSH/OpenVPN\e[0m (\e[37;1muser-renew\e[0m)"
	echo -e "  \e[032;1m 6\e[0m\e[037;1m)\e[0m \e[033;1mHapus Akun SSH/OpenVPN\e[0m (\e[37;1muser-del\e[0m)"
	echo -e "  \e[033;1m 7\e[0m\e[037;1m)\e[0m \e[033;1mCek Login Dropbear & OpenSSH\e[0m (\e[37;1muser-login\e[0m)"
	echo -e "  \e[032;1m 8\e[0m\e[037;1m)\e[0m \e[033;1mAuto Limit Multi Login\e[0m (\e[37;1mauto-limit\e[0m)"
	echo -e "  \e[032;1m 9\e[0m\e[037;1m)\e[0m \e[033;1mMelihat Detail user SSH\e[0m & OpenVPN (\e[37;1muser-detail\e[0m)"
	echo -e "  \e[032;1m10\e[0m\e[037;1m)\e[0m \e[033;1mList Akun dan Expire Date\e[0m (\e[37;1muser-list\e[0m)"
	echo -e "  \e[032;1m11\e[0m\e[037;1m)\e[0m \e[033;1mHapus Akun Expire\e[0m (\e[37;1mdelete-user-expire\e[0m)"
	echo -e "  \e[032;1m12\e[0m\e[037;1m)\e[0m \e[033;1mOn Kill Multi Login\e[0m (\e[37;1mauto-kill-user\e[0m)"
	echo -e "  \e[032;1m13\e[0m\e[037;1m)\e[0m \e[033;1mAuto Banned Akun\e[0m (\e[37;1mbanned-user\e[0m)"
	echo -e "  \e[032;1m14\e[0m\e[037;1m)\e[0m \e[033;1mUnbanned Akun\e[0m (\e[37;1munbanned-user\e[0m)"
	echo -e "  \e[032;1m15\e[0m\e[037;1m)\e[0m \e[033;1mMengunci Akun SSH & OpenVPN\e[0m (\e[37;1muser-lock\e[0m)"
	echo -e "  \e[032;1m16\e[0m\e[037;1m)\e[0m \e[033;1mMembuka User SSH & OpenVPN yang terkunci\e[0m (\e[37;1muser-unlock\e[0m)"
	echo -e "  \e[032;1m17\e[0m\e[037;1m)\e[0m \e[033;1mMelihat Daftar user yang terkick oleh perintah user-limit\e[0m (\e[37;1mlog-limit\e[0m)"
	echo -e "  \e[032;1m18\e[0m\e[037;1m)\e[0m \e[033;1mMelihat Daftar user yang terbanned oleh perintah user-ban\e[0m (\e[37;1mlog-ban\e[0m)"
        echo ""
	echo -e "\e[36mSeputar Detail PPTP VPN\e[0m"
	echo -e "  \e[032;1m19\e[0m\e[037;1m)\e[0m \e[035;1mCreate Akun PPTP VPN\e[0m (\e[37;1muser-add-pptp\e[0m)"
	echo -e "  \e[032;1m20\e[0m\e[037;1m)\e[0m \e[035;1mHapus Akun PPTP VPN\e[0m (\e[37;1muser-delete-pptp\e[0m)"
	echo -e "  \e[032;1m21\e[0m\e[037;1m)\e[0m \e[035;1mLihat Detail Akun PPTP VPN\e[0m (\e[37;1mdetail-pptp\e[0m)"
	echo -e "  \e[032;1m22\e[0m\e[037;1m)\e[0m \e[035;1mCek Login PPTP VPN\e[0m (\e[37;1muser-login-pptp\e[0m)"
	echo -e "  \e[032;1m23\e[0m\e[037;1m)\e[0m \e[035;1mLihat Daftar User PPTP VPN\e[0m (\e[37;1malluser-pptp\e[0m)"
	echo ""
	echo -e "\e[036mSeputar Detail VPS\e[0m"
	echo -e "  \e[032;1m24\e[0m\e[037;1m)\e[0m \e[034;1mSet Auto Reboot\e[0m (\e[37;1mauto-reboot\e[0m)"
	echo -e "  \e[032;1m25\e[0m\e[037;1m)\e[0m \e[034;1mSpeedtest\e[0m (\e[37;1mcek-speedttes-vps\e[0m)"
	echo -e "  \e[032;1m26\e[0m\e[037;1m)\e[0m \e[034;1mMemory Usage\e[0m (\e[37;1mps-mem\e[0m)"
	echo -e "  \e[032;1m27\e[0m\e[037;1m)\e[0m \e[034;1mUbah OpenVPN Port\e[0m (\e[37;1mchange-openvpn-port\e[0m)"
	echo -e "  \e[032;1m28\e[0m\e[037;1m)\e[0m \e[034;1mUbah Dropbear Port\e[0m (\e[37;1mchange-dropbear-port\e[0m)"
	echo -e "  \e[032;1m29\e[0m\e[037;1m)\e[0m \e[034;1mUbah Squid Port\e[0m (\e[37;1mchange-squid-port\e[0m)"
	echo -e "  \e[032;1m30\e[0m\e[037;1m)\e[0m \e[034;1mRestart OpenVPN\e[0m (\e[37;1mrestart-openvpn\e[0m)"
	echo -e "  \e[032;1m31\e[0m\e[037;1m)\e[0m \e[034;1mRestart Dropbear\e[0m (\e[37;1mrestart-dropbear\e[0m)"
	echo -e "  \e[032;1m32\e[0m\e[037;1m)\e[0m \e[034;1mRestart Squid\e[0m (\e[37;1mrestart-squid\e[0m)"
	echo -e "  \e[032;1m33\e[0m\e[037;1m)\e[0m \e[034;1mRestart Webmin\e[0m (\e[37;1mrestart-webmin\e[0m)"
	echo -e "  \e[032;1m34\e[0m\e[037;1m)\e[0m \e[034;1mBenchmark\e[0m (\e[37;1mbenchmark\e[0m)"
	echo -e "  \e[032;1m35\e[0m\e[037;1m)\e[0m \e[034;1mUbah Pasword VPS\e[0m (\e[37;1mpassword\e[0m)"
	echo -e "  \e[032;1m36\e[0m\e[037;1m)\e[0m \e[034;1mUbah Hostname VPS\e[0m (\e[37;1mhostname\e[0m)"
	echo -e "  \e[032;1m37\e[0m\e[037;1m)\e[0m \e[034;1mReboot Server\e[0m (\e[37;1mreboot\e[0m)"
	echo ""
	echo -e "\e[036mSeputar Update Premium Script\e[0m"
	echo -e "  \e[032;1m38\e[0m\e[037;1m)\e[0m \e[031;1mUpdate All Script\e[0m (\e[37;1mupdate\e[0m)"
	echo -e "  \e[032;1m39\e[0m\e[037;1m)\e[0m \e[031;1mUpdate Menu\e[0m (\e[37;1mupdate-menu\e[0m)"
	echo ""
	echo -e "    \e[032;1m x\e[0m\e[037;1m)\e[0m Exit"
	read -p "Masukkan pilihan anda, kemudian tekan tombol ENTER: " option1
	case $option1 in
        1)  
            clear
            buatakun
            ;;
        2)  
            clear
            generate
            ;;
        3)	
            clear
            trial
			;;	
        4)
            clear
            userpass
            ;;
        5)
            clear
            userrenew
			;;
        6)
            userdelete
            ;;		
		7)
		    clear
	        userlogin
			;;
		8)
		    clear
			autolimit
			;;	
		9)
		    clear
            userdetail
            ;;
		10)
		    clear
            user-list
            ;;
        11)
               clear
               deleteuserexpire
	          ;;
	    12)
	          clear
	          #!/bin/bash
              # Created by Orang Ganteng
              
              red='\e[1;31m'
              green='\e[0;32m'
              NC='\e[0m'
              echo "Connecting to Oranh-Ganteng.com..."
              sleep 0.2
			  echo "Connecting to your ip : $myip ...."
              sleep 2
              echo "Checking Permision..."
              sleep 0.3
              echo -e "${green}Permission Accepted...${NC}"
              sleep 1
               echo""
	           echo "    AUTO KILL MULTI LOGIN    "    
	           echo "-----------------------------"
               autokilluser
               echo "-----------------------------"
               echo "AUTO KILL MULTI LOGIN SELESAI"
               ;;
            13)
               clear
               userban
	          ;;
	    14)
               clear
               userunban
	          ;;
	    15)
	        clear
                userlock
			;;
		16)
		    clear
                    userunlock
			;;
		17)
		    clear
		    loglimit
			;;
		18)
		    clear
                    logban
			;;
	    19)
	        clear
            useraddpptp
			;;
		20)
		    clear
            userdeletepptp
			;;
	    21)
	        clear
            detailpptp
            ;;
        22)
            clear
            userloginpptp
			;;
		23)
		    clear
            alluserpptp
			;;
	    24)
	         clear
             autoreboot
            ;;
	    25)
	         clear
	         #!/bin/bash
            red='\e[1;31m'
            green='\e[0;32m'
            blue='\e[1;34m'
            NC='\e[0m'
            echo "Connecting to Orang-Ganteng.com..."
            sleep 0.2
			echo "Connecting to your ip : $myip ...."
            sleep 2
            echo "Checking Permision..."
            sleep 0.3
            echo -e "${green}Permission Accepted...${NC}"
            sleep 1
            echo""
            echo "Speed Test Server"
            ./speedtest.py --share
            echo "Hasil Speed test diatas Script by Orang Ganteng"
            ;;
        26)
            free -m
            ;;
		27)	
		    clear
            echo "Masukan Port OpenVPN yang diinginkan:"
            read -p "Port: " -e -i 1194 PORT
            sed -i "s/port [0-9]*/port $PORT/" /etc/openvpn/1194.conf
            service openvpn restart
            echo "OpenVPN Updated : Port $PORT"
			;;
		28)	
		    clear
            echo "Masukan Port Dropbear yang diinginkan:"
            read -p "Port: " -e -i 443 PORT
            sed -i "s/DROPBEAR_PORT=[0-9]*/DROPBEAR_PORT=$PORT/" /etc/default/dropbear
            service dropbear restart
            echo "Dropbear Updated : Port $PORT"
			;;
        29)	
            clear
            echo "Masukan Port Squid yang diinginkan:"
            read -p "Port: " -e -i 8080 PORT
            sed -i "s/http_port [0-9]*/http_port $PORT/" /etc/squid3/squid.conf
            service squid3 restart
            echo "echo "Squid3 Updated : Port $PORT""
			;;			
        30)	
            clear
            echo "Service Openvpn restart .................tunggu sebentar"
            service openvpn restart
            echo "Restart OpenVPN selesai Script By Orang Ganteng"
			;;	
		31)
            clear
            echo "Servie dropbear restart .................tunggu sebentar"
            service dropbear restart
            echo "Restart Dropbear selesai Script By Orang Ganteng"
            ;;
		32) 
		    clear
		    echo "Service Squid restart .................tunggu sebentar"
			service squid3 restart
			echo "Restart Squid selesai Script By Orang Ganteng"
			;;
		33)
		    clear
		    /etc/init.d/webmin restart
		    echo "Restart Webmin selesai Script By Orang Ganteng"
		    ;;
		34)
		    clear
            wget freevps.us/downloads/bench.sh -O - -o /dev/null|bash
           ;;
        35)
		    echo "Masukan Password VPS, yang mau diganti :"
		    passwd
			;;	
		36)
                   clear
			echo "Masukan HOSTNAME VPS, yang mau diganti :"
            echo "  contoh : " hostname Orang-Ganteng
            ;;
		37)
		    clear
			reboot
            ;;
        38)
	clear
            wget -O update https://raw.githubusercontent.com/Y4suf/MyVPS/master/config/update && chmod +x update && ./update
            clear
	    ;;
        39)
            clear
	    cd
            wget https://raw.githubusercontent.com/Y4suf/MyVPS/master/menu
            mv ./menu /usr/local/bin/menu
            chmod +x /usr/local/bin/menu
	    clear
	    ;;
        x)
            ;;
        *) menu;;
    esac
