#!/bin/bash
# Created by Orang Ganteng
            
            red='\e[1;31m'
            green='\e[0;32m'
            NC='\e[0m'
            echo "Connecting to Orang-Ganteng.com..."
            sleep 0.2
            echo "Checking Permision..."
            sleep 0.3
            echo -e "${green}Permission Accepted...${NC}"
            sleep 1
            echo""

echo "------------------------ MEMBUAT AKUN SSH ------------------------"
echo "          DEVELOPED BY Orang Ganteng . Com (089570379692)           "
echo ""

read -p "Isikan username: " username

egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
	echo "Username [$username] sudah ada!"
	exit 1
else
	read -p "Isikan password akun [$username]: " password
	read -p "Berapa hari akun [$username] aktif: " AKTIF

	today="$(date +"%Y-%m-%d")"
	expire=$(date -d "$AKTIF days" +"%Y-%m-%d")
	useradd -M -N -s /bin/false -e $expire $username
	echo $username:$password | chpasswd
echo -e ""
echo -e ""
echo -e "======================================"
echo -e "Data Login SSH PREMIUM"
echo -e "-------------------------------------"
echo -e "Host/IP: $myip" 
echo -e "Username: $username "
echo -e "Password: $password"
echo -e "    Dropbear Port: 22507, 110, 109, 80"
echo -e "    OpenSSH Port: 22, 143"
echo -e "    SSL/TLS Port: 443"
echo -e "    Port OVPN: 5555"
echo -e "    Squid Proxy: 3128, 8000, 8080"
echo -e "    Ovpn Config: http://$MYIP:81/client.ovpn"
echo -e "Aktif Sampai: $(date -d "$AKTIF days" +"%d-%b-%Y")"
echo -e "-------------------------------------"
echo -e "======================================"
echo -e "Baca & Patuhi TOS/Terms Of Service"
echo -e " NO CARDING, TORRENT, ILEGAL CONTENT"
echo -e "-------------------------------------"
echo -e "_________Powered BY BogelSSH_________"
echo -e "======================================"
echo -e ""
fi
fi
