#!/bin/bash
# Created by Orang Ganteng
            
            red='\e[1;31m'
            green='\e[0;32m'
            NC='\e[0m'
            echo "Connecting to Orang-Ganteng.com..."
            sleep 0.2
            echo "Checking Permision..."
            sleep 0.3
            echo -e "${green}Permission Accepted...${NC}"
            sleep 1
            echo""
clear
echo "------------------------ MEMBUAT AKUN SSH ------------------------"
echo "          DEVELOPED BY Orang Ganteng . Com (089570379692)           "
echo ""

read -p "Masukkan Username : " username
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
echo "Username sudah ada di VPS anda"
exit 0
else
read -p "Masukkan Password [$username]: " password
read -p "Masa Aktif Account [$username] (Hari): " masa_aktif
MYIP=$(wget -qO- ipv4.icanhazip.com)
today=`date +%s`
masa_aktif_detik=$(( $masa_aktif * 86400 ))
saat_expired=$(($today + $masa_aktif_detik))
tanggal_expired=$(date -u --date="1970-01-01 $saat_expired sec GMT" +%Y/%m/%d)
tanggal_expired_display=$(date -u --date="1970-01-01 $saat_expired sec GMT" '+%d %B %Y')

echo "Connecting to Orang-Ganteng.com..."
sleep 0.4
echo "Creating Account..."
sleep 0.3
echo "Generating Host..."
sleep 0.2
echo "Creating Your New Username: $username"
sleep 0.2
echo "Creating Password for $username"
sleep 1
clear

useradd $username
usermod -s /bin/false $username
usermod -e  $tanggal_expired $username
  egrep "^$username" /etc/passwd >/dev/null
  echo -e "$password\n$password" | passwd $username
  
echo -e ""
echo -e ""
echo -e "======================================"
echo -e "Data Login SSH PREMIUM"
echo -e "-------------------------------------"
echo -e "Host/IP: $MYIP" 
echo -e "Username: $username "
echo -e "Password: $password"
echo -e "    Dropbear Port: 22507, 110, 109, 80"
echo -e "    OpenSSH Port: 22, 143"
echo -e "    SSL/TLS Port: 443"
echo -e "    Port OVPN: 1194"
echo -e "    Squid Proxy: 8000, 8080, 3128"
echo -e "    Ovpn Config: http://$MYIP:81/client.ovpn"
echo -e "Aktif s/d: $(date -d "$AKTIF days" +"%d %b %Y")"
echo -e "-------------------------------------"
echo -e "Baca & Patuhi TOS/Terms Of Service"
echo -e " NO CARDING, TORRENT, ILEGAL CONTENT"
echo -e "-------------------------------------"
echo -e "======================================"
echo -e ""
fi
